from uniborg.util import pearl_on_cmd


@pearl.on(pearl_on_cmd(pattern=r"gaali"))
async def test(event):
    if event.fwd_from:
        return
    await event.edit(
        "`teri behen ko😃😃Mera lunddd mil jai 🤥🤥... Tere Gand Me Panaah Mil Jaye,🙈🙈🙈🙈🙈🙈🙈Uska Gand Maru💦💦💦💦 To Gand Tabah Ho Jaye,🖕🖕🖕🖕🖕🖕Raaz Chhupane Ke Liye Tu Mujhse Hi Gand Marwaye,🤣😂🤣😂🤣Aur Marwate -Marwate 😴😴😞Fana Ho Jeye…!😂🤣🤣🤣😂😂😛😛😛😛😛😛😂🤣🤣sale bhosdiwale🙄🙄🙄 teri behen ko😃😃Mera lunddd mil jai 🤥🤥... Tere Gand Me Panaah Mil Jaye,🙈🙈🙈🙈🙈🙈🙈Uska Gand Maru💦💦💦💦 To Gand Tabah Ho Jaye,🖕🖕🖕🖕🖕🖕Raaz Chhupane Ke Liye Tu Mujhse Hi Gand Marwaye,🤣😂🤣😂🤣Aur Marwate -Marwate 😴😴😞Fana Ho Jeye…!😂🤣🤣🤣😂😂😛😛😛😛😛😛😂🤣🤣sale bhosdiwale🙄🙄🙄 teri behen ko😃😃Mera lunddd mil jai 🤥🤥... Tere Gand Me Panaah Mil Jaye,🙈🙈🙈🙈🙈🙈🙈Uska Gand Maru💦💦💦💦 To Gand Tabah Ho Jaye,🖕🖕🖕🖕🖕🖕Raaz Chhupane Ke Liye Tu Mujhse Hi Gand Marwaye,🤣😂🤣😂🤣Aur Marwate -Marwate 😴😴😞Fana Ho Jeye…!😂🤣🤣🤣😂😂😛😛😛😛😛😛😂🤣🤣sale sasti randi k bacche🙄🙄🙄 teri behen ko😃😃Mera lunddd mil jai 🤥🤥... Tere Gand Me Panaah Mil Jaye,🙈🙈🙈🙈🙈🙈🙈Uska Gand Maru💦💦💦💦 To Gand Tabah Ho Jaye,🖕🖕🖕🖕🖕🖕Raaz Chhupane Ke Liye Tu Mujhse Hi Gand Marwaye,🤣😂🤣😂🤣Aur Marwate -Marwate 😴😴😞Fana Ho Jeye…!😂🤣🤣🤣😂😂😛😛😛😛😛😛😂🤣🤣😈𒆜★彡༺( ₮ɆⱤ₳ ฿₳₳₱ {քɨȶǟʝɨ}༺𒆜★彡😈🔱 TERI MAA KO ITNA CHODA KI WO MAR GYI AUR USKA ANTIM SANSKAR VI NHI HO PAYA APNI MAMI MT CHUDAO BETE AB APNI MOSI KO VEJO USHE CHODUNGA TERI MAA KA CHUT MAI JCB SE KADAR DUNGA RANDI KE BACHE SUWAR KI OLAD BEHENCHOD KI GAND SALE TAATI KE PAIDAIS TERE GAND MAI YESA LODA MARUNGA NA KAHI GAND DENE LAKYAK NHI RAHEGA🔥💦💦💦💦💦💦💦💦💦💦💦 TERI BEHEN KI GAND MAI APNA MOTHA SA HATORA GUSAUNGA NA MAAJA AAGYEGA💦💦💦💦`"
    )
